#!/bin/sh
##############################################################################
# Copyright (C) 2012 divreg <wyatt.brege@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# Author: Wyatt Brege <wyatt.brege@gmail.com>
#
# Date: Fri May 11 2012
# Version 1.1
#
##############################################################################

function echolog {
echo "`date +'%m/%d/%Y %H:%M:%S'` - $1"
}

flacdir="/storage/music/flac"
oggdir="/storage/music/ogg"

if [ -f /etc/vortexbox/oggopt.txt ]; then
  qualoggenc="`cat /etc/vortexbox/oggopt.txt`"
  oggencopt="-o"
  echo "$oggopt"
  echo "Using $qualoggenc to encode Ogg Vorbis." >> /var/log/mirror.log &
else
	qualoggenc="-q6"
  oggencopt="-o"
  echo "No default quality selected.  Using -q6 (192 kbit/s)" >> /var/log/mirror.log &
fi

touch /etc/vortexbox/mirror-flac-ogg.running

/usr/local/sbin/flac2ogg.sh "$flacdir" $qualoggenc $oggencopt "$oggdir" 

rm /etc/vortexbox/mirror-flac-ogg.running

echo ""
echolog "Mirroring FLACs to Ogg Vorbis done." >> /var/log/mirror.log
echo ""
