#!/bin/sh
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

function echolog {
echo "`date +'%m/%d/%Y %H:%M:%S'` - $1"
}

oggopt="`cat /etc/vortexbox/oggopt.txt` -o"

touch /etc/vortexbox/mirror-flac-ogg.running

/usr/local/sbin/flac2ogg.sh "/storage/music/flac" "$oggopt" "/storage/music/ogg"

rm /etc/vortexbox/mirror-flac-ogg.running

echo ""
echo "Done."
echolog "Mirroring FLACs to Ogg Vorbis done." >> /var/log/mirror.log
echo ""
