<?php
// Copyright (C) 2008 - 2012 vortexbox.org
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
require '/var/www/html/libs/Smarty.class.php';

$smarty = new Smarty;
$smarty->caching = 0;

$smarty->compile_check = true;
$smarty->debugging = false;

require '/var/www/html/libs/vortexbox_defs.php';
require '/var/www/html/libs/vortexbox_smarty.php';

//default timezone
$TIMEZONE = "America/New_York";

$_action = isset($_REQUEST['action']) ? $_REQUEST['action'] : 'default';
if (isset($_REQUEST['TIMEZONE']) & !$_REQUEST['TIMEZONE'] =="") { $TIMEZONE = $_REQUEST['TIMEZONE']; }
if (isset($_REQUEST['TEMPFORMAT']) & !$_REQUEST['TEMPFORMAT'] =="") { $TempFormat= $_REQUEST['TEMPFORMAT']; }
if (isset($_REQUEST['service']) & !$_REQUEST['service'] =="") { $service= $_REQUEST['service']; }

switch($_action) {

    case 'submit':
		if ( $TIMEZONE[0] != "-" ) {
		exec("sudo /opt/vortexbox/doaction.sh NewTZ $TIMEZONE & >/dev/null 2>&1");
		}
		exec("echo ".$TempFormat." > /etc/vortexbox/tempformat.conf");
        break;
	case 'Reboot':
		exec("sudo /opt/vortexbox/doaction.sh Reboot & >/dev/null 2>&1");
        break;
	case 'PowerDown':
		exec("sudo /opt/vortexbox/doaction.sh PowerDown & >/dev/null 2>&1");
        break;
	case 'SyncTime':
		exec("sudo /opt/vortexbox/doaction.sh SyncTime & >/dev/null 2>&1");
        break;
    default:
	
        break;
}

if (file_exists("/etc/vortexbox/tempformat.conf")) {
    $TempFormat = exec("cat /etc/vortexbox/tempformat.conf");
} else {
    $TempFormat ="f";
}

$CurrentTimeZone = exec("cat /etc/sysconfig/clock | awk '/ZONE/ {split ($1,A,\"\\\"\"); print A[2]}'");

$smarty->assign('CurrentTempFormat', $TempFormat);
$smarty->assign('TempFormatList', array('f' => 'Fahrenheit', 'c' => 'Celsius'));


$smarty->assign('CURRENTTIMEZONE', $CurrentTimeZone);
//current date and time + timezone
$smarty->assign('CurrentDate', exec("date"));

$smarty->assign('tzlist', array(
'Africa/Abidjan' => 'Africa/Abidjan',
'Africa/Accra' => 'Africa/Accra',
'Africa/Addis_Ababa' => 'Africa/Addis_Ababa',
'Africa/Algiers' => 'Africa/Algiers',
'Africa/Asmara' => 'Africa/Asmara',
'Africa/Bamako' => 'Africa/Bamako',
'Africa/Bangui' => 'Africa/Bangui',
'Africa/Banjul' => 'Africa/Banjul',
'Africa/Bissau' => 'Africa/Bissau',
'Africa/Blantyre' => 'Africa/Blantyre',
'Africa/Brazzaville' => 'Africa/Brazzaville',
'Africa/Bujumbura' => 'Africa/Bujumbura',
'Africa/Cairo' => 'Africa/Cairo',
'Africa/Casablanca' => 'Africa/Casablanca',
'Africa/Ceuta' => 'Africa/Ceuta (Ceuta & Melilla)',
'Africa/Conakry' => 'Africa/Conakry',
'Africa/Dakar' => 'Africa/Dakar',
'Africa/Dar_es_Salaam' => 'Africa/Dar_es_Salaam',
'Africa/Djibouti' => 'Africa/Djibouti',
'Africa/Douala' => 'Africa/Douala',
'Africa/El_Aaiun' => 'Africa/El_Aaiun',
'Africa/Freetown' => 'Africa/Freetown',
'Africa/Gaborone' => 'Africa/Gaborone',
'Africa/Harare' => 'Africa/Harare',
'Africa/Johannesburg' => 'Africa/Johannesburg',
'Africa/Kampala' => 'Africa/Kampala',
'Africa/Khartoum' => 'Africa/Khartoum',
'Africa/Kigali' => 'Africa/Kigali',
'Africa/Kinshasa' => 'Africa/Kinshasa (west Dem. Rep. of Congo)',
'Africa/Lagos' => 'Africa/Lagos',
'Africa/Libreville' => 'Africa/Libreville',
'Africa/Lome' => 'Africa/Lome',
'Africa/Luanda' => 'Africa/Luanda',
'Africa/Lubumbashi' => 'Africa/Lubumbashi (east Dem. Rep. of Congo)',
'Africa/Lusaka' => 'Africa/Lusaka',
'Africa/Malabo' => 'Africa/Malabo',
'Africa/Maputo' => 'Africa/Maputo',
'Africa/Maseru' => 'Africa/Maseru',
'Africa/Mbabane' => 'Africa/Mbabane',
'Africa/Mogadishu' => 'Africa/Mogadishu',
'Africa/Monrovia' => 'Africa/Monrovia',
'Africa/Nairobi' => 'Africa/Nairobi',
'Africa/Ndjamena' => 'Africa/Ndjamena',
'Africa/Niamey' => 'Africa/Niamey',
'Africa/Nouakchott' => 'Africa/Nouakchott',
'Africa/Ouagadougou' => 'Africa/Ouagadougou',
'Africa/Porto-Novo' => 'Africa/Porto-Novo',
'Africa/Sao_Tome' => 'Africa/Sao_Tome',
'Africa/Tripoli' => 'Africa/Tripoli',
'Africa/Tunis' => 'Africa/Tunis',
'Africa/Windhoek' => 'Africa/Windhoek',
'-1' => '----------',
'America/Adak' => 'America/Adak (Aleutian Islands)',
'America/Anchorage' => 'America/Anchorage (Alaska Time)',
'America/Anguilla' => 'America/Anguilla',
'America/Antigua' => 'America/Antigua',
'America/Araguaina' => 'America/Araguaina (Tocantins)',
'-2' => '----------',
'America/Argentina/Buenos_Aires' => 'America/Argentina/Buenos_Aires (Buenos Aires (BA, CF))',
'America/Argentina/Catamarca' => 'America/Argentina/Catamarca (Catamarca (CT), Chubut (CH))',
'America/Argentina/Cordoba' => 'America/Argentina/Cordoba (most locations (CB, CC, CN, ER, FM, MN, SE, SF))',
'America/Argentina/Jujuy' => 'America/Argentina/Jujuy (Jujuy (JY))',
'America/Argentina/La_Rioja' => 'America/Argentina/La_Rioja (La Rioja (LR))',
'America/Argentina/Mendoza' => 'America/Argentina/Mendoza (Mendoza (MZ))',
'America/Argentina/Rio_Gallegos' => 'America/Argentina/Rio_Gallegos (Santa Cruz (SC))',
'America/Argentina/Salta' => 'America/Argentina/Salta ((SA, LP, NQ, RN))',
'America/Argentina/San_Juan' => 'America/Argentina/San_Juan (San Juan (SJ))',
'America/Argentina/San_Luis' => 'America/Argentina/San_Luis (San Luis (SL))',
'America/Argentina/Tucuman' => 'America/Argentina/Tucuman (Tucuman (TM))',
'America/Argentina/Ushuaia' => 'America/Argentina/Ushuaia (Tierra del Fuego (TF))',
'-3' => '----------',
'America/Aruba' => 'America/Aruba',
'America/Asuncion' => 'America/Asuncion',
'America/Atikokan' => 'America/Atikokan (Eastern Standard Time - Atikokan, Ontario and Southampton I, Nunavut)',
'America/Bahia' => 'America/Bahia (Bahia)',
'America/Barbados' => 'America/Barbados',
'America/Belem' => 'America/Belem (Amapa, E Para)',
'America/Belize' => 'America/Belize',
'America/Blanc-Sablon' => 'America/Blanc-Sablon (Atlantic Standard Time - Quebec - Lower North Shore)',
'America/Boa_Vista' => 'America/Boa_Vista (Roraima)',
'America/Bogota' => 'America/Bogota',
'America/Boise' => 'America/Boise (Mountain Time - south Idaho & east Oregon)',
'America/Cambridge_Bay' => 'America/Cambridge_Bay (Mountain Time - west Nunavut)',
'America/Campo_Grande' => 'America/Campo_Grande (Mato Grosso do Sul)',
'America/Cancun' => 'America/Cancun (Central Time - Quintana Roo)',
'America/Caracas' => 'America/Caracas',
'America/Cayenne' => 'America/Cayenne',
'America/Cayman' => 'America/Cayman',
'America/Chicago' => 'America/Chicago (Central Time)',
'America/Chihuahua' => 'America/Chihuahua (Mountain Time - Chihuahua)',
'America/Costa_Rica' => 'America/Costa_Rica',
'America/Cuiaba' => 'America/Cuiaba (Mato Grosso)',
'America/Curacao' => 'America/Curacao',
'America/Danmarkshavn' => 'America/Danmarkshavn (east coast, north of Scoresbysund)',
'America/Dawson' => 'America/Dawson (Pacific Time - north Yukon)',
'America/Dawson_Creek' => 'America/Dawson_Creek (Mountain Standard Time - Dawson Creek & Fort Saint John, British Columbia)',
'America/Denver' => 'America/Denver (Mountain Time)',
'America/Detroit' => 'America/Detroit (Eastern Time - Michigan - most locations)',
'America/Dominica' => 'America/Dominica',
'America/Edmonton' => 'America/Edmonton (Mountain Time - Alberta, east British Columbia & west Saskatchewan)',
'America/Eirunepe' => 'America/Eirunepe (W Amazonas)',
'America/El_Salvador' => 'America/El_Salvador',
'America/Fortaleza' => 'America/Fortaleza (NE Brazil (MA, PI, CE, RN, PB))',
'America/Glace_Bay' => 'America/Glace_Bay (Atlantic Time - Nova Scotia - places that did not observe DST 1966-1971)',
'America/Godthab' => 'America/Godthab (most locations)',
'America/Goose_Bay' => 'America/Goose_Bay (Atlantic Time - Labrador - most locations)',
'America/Grand_Turk' => 'America/Grand_Turk',
'America/Grenada' => 'America/Grenada',
'America/Guadeloupe' => 'America/Guadeloupe',
'America/Guatemala' => 'America/Guatemala',
'America/Guayaquil' => 'America/Guayaquil (mainland)',
'America/Guyana' => 'America/Guyana',
'America/Halifax' => 'America/Halifax (Atlantic Time - Nova Scotia (most places), PEI)',
'America/Havana' => 'America/Havana',
'America/Hermosillo' => 'America/Hermosillo (Mountain Standard Time - Sonora)',
'-4' => '----------',
'America/Indiana/Indianapolis' => 'America/Indiana/Indianapolis (Eastern Time - Indiana - most locations)',
'America/Indiana/Knox' => 'America/Indiana/Knox (Central Time - Indiana - Starke County)',
'America/Indiana/Marengo' => 'America/Indiana/Marengo (Eastern Time - Indiana - Crawford County)',
'America/Indiana/Petersburg' => 'America/Indiana/Petersburg (Eastern Time - Indiana - Pike County)',
'America/Indiana/Tell_City' => 'America/Indiana/Tell_City (Central Time - Indiana - Perry County)',
'America/Indiana/Vevay' => 'America/Indiana/Vevay (Eastern Time - Indiana - Switzerland County)',
'America/Indiana/Vincennes' => 'America/Indiana/Vincennes (Eastern Time - Indiana - Daviess, Dubois, Knox & Martin Counties)',
'America/Indiana/Winamac' => 'America/Indiana/Winamac (Eastern Time - Indiana - Pulaski County)',
'-5' => '----------',
'America/Inuvik' => 'America/Inuvik (Mountain Time - west Northwest Territories)',
'America/Iqaluit' => 'America/Iqaluit (Eastern Time - east Nunavut - most locations)',
'America/Jamaica' => 'America/Jamaica',
'America/Juneau' => 'America/Juneau (Alaska Time - Alaska panhandle)',
'-6' => '----------',
'America/Kentucky/Louisville' => 'America/Kentucky/Louisville (Eastern Time - Kentucky - Louisville area)',
'America/Kentucky/Monticello' => 'America/Kentucky/Monticello (Eastern Time - Kentucky - Wayne County)',
'-7' => '----------',
'America/La_Paz' => 'America/La_Paz',
'America/Lima' => 'America/Lima',
'America/Los_Angeles' => 'America/Los_Angeles (Pacific Time)',
'America/Maceio' => 'America/Maceio (Alagoas, Sergipe)',
'America/Managua' => 'America/Managua',
'America/Manaus' => 'America/Manaus (E Amazonas)',
'America/Marigot' => 'America/Marigot',
'America/Martinique' => 'America/Martinique',
'America/Mazatlan' => 'America/Mazatlan (Mountain Time - S Baja, Nayarit, Sinaloa)',
'America/Menominee' => 'America/Menominee (Central Time - Michigan - Dickinson, Gogebic, Iron & Menominee Counties)',
'America/Merida' => 'America/Merida (Central Time - Campeche, Yucatan)',
'America/Mexico_City' => 'America/Mexico_City (Central Time - most locations)',
'America/Miquelon' => 'America/Miquelon',
'America/Moncton' => 'America/Moncton (Atlantic Time - New Brunswick)',
'America/Monterrey' => 'America/Monterrey (Central Time - Coahuila, Durango, Nuevo Leon, Tamaulipas)',
'America/Montevideo' => 'America/Montevideo',
'America/Montreal' => 'America/Montreal (Eastern Time - Quebec - most locations)',
'America/Montserrat' => 'America/Montserrat',
'America/Nassau' => 'America/Nassau',
'America/New_York' => 'America/New_York (Eastern Time)',
'America/Nipigon' => 'America/Nipigon (Eastern Time - Ontario & Quebec - places that did not observe DST 1967-1973)',
'America/Nome' => 'America/Nome (Alaska Time - west Alaska)',
'America/Noronha' => 'America/Noronha (Atlantic islands)',
'-8' => '----------',
'America/North_Dakota/Center' => 'America/North_Dakota/Center (Central Time - North Dakota - Oliver County)',
'America/North_Dakota/New_Salem' => 'America/North_Dakota/New_Salem (Central Time - North Dakota - Morton County (except Mandan area))',
'-9' => '----------',
'America/Panama' => 'America/Panama',
'America/Pangnirtung' => 'America/Pangnirtung (Eastern Time - Pangnirtung, Nunavut)',
'America/Paramaribo' => 'America/Paramaribo',
'America/Phoenix' => 'America/Phoenix (Mountain Standard Time - Arizona)',
'America/Port-au-Prince' => 'America/Port-au-Prince',
'America/Port_of_Spain' => 'America/Port_of_Spain',
'America/Porto_Velho' => 'America/Porto_Velho (Rondonia)',
'America/Puerto_Rico' => 'America/Puerto_Rico',
'America/Rainy_River' => 'America/Rainy_River (Central Time - Rainy River & Fort Frances, Ontario)',
'America/Rankin_Inlet' => 'America/Rankin_Inlet (Central Time - central Nunavut)',
'America/Recife' => 'America/Recife (Pernambuco)',
'America/Regina' => 'America/Regina (Central Standard Time - Saskatchewan - most locations)',
'America/Resolute' => 'America/Resolute (Eastern Standard Time - Resolute, Nunavut)',
'America/Rio_Branco' => 'America/Rio_Branco (Acre)',
'America/Santarem' => 'America/Santarem (W Para)',
'America/Santiago' => 'America/Santiago (most locations)',
'America/Santo_Domingo' => 'America/Santo_Domingo',
'America/Sao_Paulo' => 'America/Sao_Paulo (S & SE Brazil (GO, DF, MG, ES, RJ, SP, PR, SC, RS))',
'America/Scoresbysund' => 'America/Scoresbysund (Scoresbysund / Ittoqqortoormiit)',
'America/Shiprock' => 'America/Shiprock (Mountain Time - Navajo)',
'America/St_Barthelemy' => 'America/St_Barthelemy',
'America/St_Johns' => 'America/St_Johns (Newfoundland Time, including SE Labrador)',
'America/St_Kitts' => 'America/St_Kitts',
'America/St_Lucia' => 'America/St_Lucia',
'America/St_Thomas' => 'America/St_Thomas',
'America/St_Vincent' => 'America/St_Vincent',
'America/Swift_Current' => 'America/Swift_Current (Central Standard Time - Saskatchewan - midwest)',
'America/Tegucigalpa' => 'America/Tegucigalpa',
'America/Thule' => 'America/Thule (Thule / Pituffik)',
'America/Thunder_Bay' => 'America/Thunder_Bay (Eastern Time - Thunder Bay, Ontario)',
'America/Tijuana' => 'America/Tijuana (Pacific Time)',
'America/Toronto' => 'America/Toronto (Eastern Time - Ontario - most locations)',
'America/Tortola' => 'America/Tortola',
'America/Vancouver' => 'America/Vancouver (Pacific Time - west British Columbia)',
'America/Whitehorse' => 'America/Whitehorse (Pacific Time - south Yukon)',
'America/Winnipeg' => 'America/Winnipeg (Central Time - Manitoba & west Ontario)',
'America/Yakutat' => 'America/Yakutat (Alaska Time - Alaska panhandle neck)',
'America/Yellowknife' => 'America/Yellowknife (Mountain Time - central Northwest Territories)',
'-10' => '----------',
'Antarctica/Casey' => 'Antarctica/Casey (Casey Station, Bailey Peninsula)',
'Antarctica/Davis' => 'Antarctica/Davis (Davis Station, Vestfold Hills)',
'Antarctica/DumontDUrville' => 'Antarctica/DumontDUrville (Dumont-d\'Urville Station, Terre Adelie)',
'Antarctica/Mawson' => 'Antarctica/Mawson (Mawson Station, Holme Bay)',
'Antarctica/McMurdo' => 'Antarctica/McMurdo (McMurdo Station, Ross Island)',
'Antarctica/Palmer' => 'Antarctica/Palmer (Palmer Station, Anvers Island)',
'Antarctica/Rothera' => 'Antarctica/Rothera (Rothera Station, Adelaide Island)',
'Antarctica/South_Pole' => 'Antarctica/South_Pole (Amundsen-Scott Station, South Pole)',
'Antarctica/Syowa' => 'Antarctica/Syowa (Syowa Station, E Ongul I)',
'Antarctica/Vostok' => 'Antarctica/Vostok (Vostok Station, S Magnetic Pole)',
'-11' => '----------',
'Arctic/Longyearbyen' => 'Arctic/Longyearbyen',
'-12' => '----------',
'Asia/Aden' => 'Asia/Aden',
'Asia/Almaty' => 'Asia/Almaty (most locations)',
'Asia/Amman' => 'Asia/Amman',
'Asia/Anadyr' => 'Asia/Anadyr (Moscow+10 - Bering Sea)',
'Asia/Aqtau' => 'Asia/Aqtau (Atyrau (Atirau, Gur\'yev), Mangghystau (Mankistau))',
'Asia/Aqtobe' => 'Asia/Aqtobe (Aqtobe (Aktobe))',
'Asia/Ashgabat' => 'Asia/Ashgabat',
'Asia/Baghdad' => 'Asia/Baghdad',
'Asia/Bahrain' => 'Asia/Bahrain',
'Asia/Baku' => 'Asia/Baku',
'Asia/Bangkok' => 'Asia/Bangkok',
'Asia/Beirut' => 'Asia/Beirut',
'Asia/Bishkek' => 'Asia/Bishkek',
'Asia/Brunei' => 'Asia/Brunei',
'Asia/Choibalsan' => 'Asia/Choibalsan (Dornod, Sukhbaatar)',
'Asia/Chongqing' => 'Asia/Chongqing (central China - Sichuan, Yunnan, Guangxi, Shaanxi, Guizhou, etc.)',
'Asia/Colombo' => 'Asia/Colombo',
'Asia/Damascus' => 'Asia/Damascus',
'Asia/Dhaka' => 'Asia/Dhaka',
'Asia/Dili' => 'Asia/Dili',
'Asia/Dubai' => 'Asia/Dubai',
'Asia/Dushanbe' => 'Asia/Dushanbe',
'Asia/Gaza' => 'Asia/Gaza',
'Asia/Harbin' => 'Asia/Harbin (Heilongjiang (except Mohe), Jilin)',
'Asia/Ho_Chi_Minh' => 'Asia/Ho_Chi_Minh',
'Asia/Hong_Kong' => 'Asia/Hong_Kong',
'Asia/Hovd' => 'Asia/Hovd (Bayan-Olgiy, Govi-Altai, Hovd, Uvs, Zavkhan)',
'Asia/Irkutsk' => 'Asia/Irkutsk (Moscow+05 - Lake Baikal)',
'Asia/Jakarta' => 'Asia/Jakarta (Java & Sumatra)',
'Asia/Jayapura' => 'Asia/Jayapura (Irian Jaya & the Moluccas)',
'Asia/Jerusalem' => 'Asia/Jerusalem',
'Asia/Kabul' => 'Asia/Kabul',
'Asia/Kamchatka' => 'Asia/Kamchatka (Moscow+09 - Kamchatka)',
'Asia/Karachi' => 'Asia/Karachi',
'Asia/Kashgar' => 'Asia/Kashgar (west Tibet & Xinjiang)',
'Asia/Kathmandu' => 'Asia/Kathmandu',
'Asia/Kolkata' => 'Asia/Kolkata',
'Asia/Krasnoyarsk' => 'Asia/Krasnoyarsk (Moscow+04 - Yenisei River)',
'Asia/Kuala_Lumpur' => 'Asia/Kuala_Lumpur (peninsular Malaysia)',
'Asia/Kuching' => 'Asia/Kuching (Sabah & Sarawak)',
'Asia/Kuwait' => 'Asia/Kuwait',
'Asia/Macau' => 'Asia/Macau',
'Asia/Magadan' => 'Asia/Magadan (Moscow+08 - Magadan)',
'Asia/Makassar' => 'Asia/Makassar (east & south Borneo, Celebes, Bali, Nusa Tengarra, west Timor)',
'Asia/Manila' => 'Asia/Manila',
'Asia/Muscat' => 'Asia/Muscat',
'Asia/Nicosia' => 'Asia/Nicosia',
'Asia/Novosibirsk' => 'Asia/Novosibirsk (Moscow+03 - Novosibirsk)',
'Asia/Omsk' => 'Asia/Omsk (Moscow+03 - west Siberia)',
'Asia/Oral' => 'Asia/Oral (West Kazakhstan)',
'Asia/Phnom_Penh' => 'Asia/Phnom_Penh',
'Asia/Pontianak' => 'Asia/Pontianak (west & central Borneo)',
'Asia/Pyongyang' => 'Asia/Pyongyang',
'Asia/Qatar' => 'Asia/Qatar',
'Asia/Qyzylorda' => 'Asia/Qyzylorda (Qyzylorda (Kyzylorda, Kzyl-Orda))',
'Asia/Rangoon' => 'Asia/Rangoon',
'Asia/Riyadh' => 'Asia/Riyadh',
'Asia/Sakhalin' => 'Asia/Sakhalin (Moscow+07 - Sakhalin Island)',
'Asia/Samarkand' => 'Asia/Samarkand (west Uzbekistan)',
'Asia/Seoul' => 'Asia/Seoul',
'Asia/Shanghai' => 'Asia/Shanghai (east China - Beijing, Guangdong, Shanghai, etc.)',
'Asia/Singapore' => 'Asia/Singapore',
'Asia/Taipei' => 'Asia/Taipei',
'Asia/Tashkent' => 'Asia/Tashkent (east Uzbekistan)',
'Asia/Tbilisi' => 'Asia/Tbilisi',
'Asia/Tehran' => 'Asia/Tehran',
'Asia/Thimphu' => 'Asia/Thimphu',
'Asia/Tokyo' => 'Asia/Tokyo',
'Asia/Ulaanbaatar' => 'Asia/Ulaanbaatar (most locations)',
'Asia/Urumqi' => 'Asia/Urumqi (most of Tibet & Xinjiang)',
'Asia/Vientiane' => 'Asia/Vientiane',
'Asia/Vladivostok' => 'Asia/Vladivostok (Moscow+07 - Amur River)',
'Asia/Yakutsk' => 'Asia/Yakutsk (Moscow+06 - Lena River)',
'Asia/Yekaterinburg' => 'Asia/Yekaterinburg (Moscow+02 - Urals)',
'Asia/Yerevan' => 'Asia/Yerevan',
'-13' => '----------',
'Atlantic/Azores' => 'Atlantic/Azores (Azores)',
'Atlantic/Bermuda' => 'Atlantic/Bermuda',
'Atlantic/Canary' => 'Atlantic/Canary (Canary Islands)',
'Atlantic/Cape_Verde' => 'Atlantic/Cape_Verde',
'Atlantic/Faroe' => 'Atlantic/Faroe',
'Atlantic/Madeira' => 'Atlantic/Madeira (Madeira Islands)',
'Atlantic/Reykjavik' => 'Atlantic/Reykjavik',
'Atlantic/South_Georgia' => 'Atlantic/South_Georgia',
'Atlantic/St_Helena' => 'Atlantic/St_Helena',
'Atlantic/Stanley' => 'Atlantic/Stanley',
'-14' => '----------',
'Australia/Adelaide' => 'Australia/Adelaide (South Australia)',
'Australia/Brisbane' => 'Australia/Brisbane (Queensland - most locations)',
'Australia/Broken_Hill' => 'Australia/Broken_Hill (New South Wales - Yancowinna)',
'Australia/Currie' => 'Australia/Currie (Tasmania - King Island)',
'Australia/Darwin' => 'Australia/Darwin (Northern Territory)',
'Australia/Eucla' => 'Australia/Eucla (Western Australia - Eucla area)',
'Australia/Hobart' => 'Australia/Hobart (Tasmania - most locations)',
'Australia/Lindeman' => 'Australia/Lindeman (Queensland - Holiday Islands)',
'Australia/Lord_Howe' => 'Australia/Lord_Howe (Lord Howe Island)',
'Australia/Melbourne' => 'Australia/Melbourne (Victoria)',
'Australia/Perth' => 'Australia/Perth (Western Australia - most locations)',
'Australia/Sydney' => 'Australia/Sydney (New South Wales - most locations)',
'-15' => '----------',
'Europe/Amsterdam' => 'Europe/Amsterdam',
'Europe/Andorra' => 'Europe/Andorra',
'Europe/Athens' => 'Europe/Athens',
'Europe/Belgrade' => 'Europe/Belgrade',
'Europe/Berlin' => 'Europe/Berlin',
'Europe/Bratislava' => 'Europe/Bratislava',
'Europe/Brussels' => 'Europe/Brussels',
'Europe/Bucharest' => 'Europe/Bucharest',
'Europe/Budapest' => 'Europe/Budapest',
'Europe/Chisinau' => 'Europe/Chisinau',
'Europe/Copenhagen' => 'Europe/Copenhagen',
'Europe/Dublin' => 'Europe/Dublin',
'Europe/Gibraltar' => 'Europe/Gibraltar',
'Europe/Guernsey' => 'Europe/Guernsey',
'Europe/Helsinki' => 'Europe/Helsinki',
'Europe/Isle_of_Man' => 'Europe/Isle_of_Man',
'Europe/Istanbul' => 'Europe/Istanbul',
'Europe/Jersey' => 'Europe/Jersey',
'Europe/Kaliningrad' => 'Europe/Kaliningrad (Moscow-01 - Kaliningrad)',
'Europe/Kiev' => 'Europe/Kiev (most locations)',
'Europe/Lisbon' => 'Europe/Lisbon (mainland)',
'Europe/Ljubljana' => 'Europe/Ljubljana',
'Europe/London' => 'Europe/London',
'Europe/Luxembourg' => 'Europe/Luxembourg',
'Europe/Madrid' => 'Europe/Madrid (mainland)',
'Europe/Malta' => 'Europe/Malta',
'Europe/Mariehamn' => 'Europe/Mariehamn',
'Europe/Minsk' => 'Europe/Minsk',
'Europe/Monaco' => 'Europe/Monaco',
'Europe/Moscow' => 'Europe/Moscow (Moscow+00 - west Russia)',
'Europe/Oslo' => 'Europe/Oslo',
'Europe/Paris' => 'Europe/Paris',
'Europe/Podgorica' => 'Europe/Podgorica',
'Europe/Prague' => 'Europe/Prague',
'Europe/Riga' => 'Europe/Riga',
'Europe/Rome' => 'Europe/Rome',
'Europe/Samara' => 'Europe/Samara (Moscow+01 - Samara, Udmurtia)',
'Europe/San_Marino' => 'Europe/San_Marino',
'Europe/Sarajevo' => 'Europe/Sarajevo',
'Europe/Simferopol' => 'Europe/Simferopol (central Crimea)',
'Europe/Skopje' => 'Europe/Skopje',
'Europe/Sofia' => 'Europe/Sofia',
'Europe/Stockholm' => 'Europe/Stockholm',
'Europe/Tallinn' => 'Europe/Tallinn',
'Europe/Tirane' => 'Europe/Tirane',
'Europe/Uzhgorod' => 'Europe/Uzhgorod (Ruthenia)',
'Europe/Vaduz' => 'Europe/Vaduz',
'Europe/Vatican' => 'Europe/Vatican',
'Europe/Vienna' => 'Europe/Vienna',
'Europe/Vilnius' => 'Europe/Vilnius',
'Europe/Volgograd' => 'Europe/Volgograd (Moscow+00 - Caspian Sea)',
'Europe/Warsaw' => 'Europe/Warsaw',
'Europe/Zagreb' => 'Europe/Zagreb',
'Europe/Zaporozhye' => 'Europe/Zaporozhye (Zaporozh\'ye, E Lugansk / Zaporizhia, E Luhansk)',
'Europe/Zurich' => 'Europe/Zurich',
'-16' => '----------',
'GMT' => 'GMT (GMT)',
'-17' => '----------',
'Indian/Antananarivo' => 'Indian/Antananarivo',
'Indian/Chagos' => 'Indian/Chagos',
'Indian/Christmas' => 'Indian/Christmas',
'Indian/Cocos' => 'Indian/Cocos',
'Indian/Comoro' => 'Indian/Comoro',
'Indian/Kerguelen' => 'Indian/Kerguelen',
'Indian/Mahe' => 'Indian/Mahe',
'Indian/Maldives' => 'Indian/Maldives',
'Indian/Mauritius' => 'Indian/Mauritius',
'Indian/Mayotte' => 'Indian/Mayotte',
'Indian/Reunion' => 'Indian/Reunion',
'-18' => '----------',
'Pacific/Apia' => 'Pacific/Apia',
'Pacific/Auckland' => 'Pacific/Auckland (most locations)',
'Pacific/Chatham' => 'Pacific/Chatham (Chatham Islands)',
'Pacific/Easter' => 'Pacific/Easter (Easter Island & Sala y Gomez)',
'Pacific/Efate' => 'Pacific/Efate',
'Pacific/Enderbury' => 'Pacific/Enderbury (Phoenix Islands)',
'Pacific/Fakaofo' => 'Pacific/Fakaofo',
'Pacific/Fiji' => 'Pacific/Fiji',
'Pacific/Funafuti' => 'Pacific/Funafuti',
'Pacific/Galapagos' => 'Pacific/Galapagos (Galapagos Islands)',
'Pacific/Gambier' => 'Pacific/Gambier (Gambier Islands)',
'Pacific/Guadalcanal' => 'Pacific/Guadalcanal',
'Pacific/Guam' => 'Pacific/Guam',
'Pacific/Honolulu' => 'Pacific/Honolulu (Hawaii)',
'Pacific/Johnston' => 'Pacific/Johnston (Johnston Atoll)',
'Pacific/Kiritimati' => 'Pacific/Kiritimati (Line Islands)',
'Pacific/Kosrae' => 'Pacific/Kosrae (Kosrae)',
'Pacific/Kwajalein' => 'Pacific/Kwajalein (Kwajalein)',
'Pacific/Majuro' => 'Pacific/Majuro (most locations)',
'Pacific/Marquesas' => 'Pacific/Marquesas (Marquesas Islands)',
'Pacific/Midway' => 'Pacific/Midway (Midway Islands)',
'Pacific/Nauru' => 'Pacific/Nauru',
'Pacific/Niue' => 'Pacific/Niue',
'Pacific/Norfolk' => 'Pacific/Norfolk',
'Pacific/Noumea' => 'Pacific/Noumea',
'Pacific/Pago_Pago' => 'Pacific/Pago_Pago',
'Pacific/Palau' => 'Pacific/Palau',
'Pacific/Pitcairn' => 'Pacific/Pitcairn',
'Pacific/Ponape' => 'Pacific/Ponape (Ponape (Pohnpei))',
'Pacific/Port_Moresby' => 'Pacific/Port_Moresby',
'Pacific/Rarotonga' => 'Pacific/Rarotonga',
'Pacific/Saipan' => 'Pacific/Saipan',
'Pacific/Tahiti' => 'Pacific/Tahiti (Society Islands)',
'Pacific/Tarawa' => 'Pacific/Tarawa (Gilbert Islands)',
'Pacific/Tongatapu' => 'Pacific/Tongatapu',
'Pacific/Truk' => 'Pacific/Truk (Truk (Chuuk) and Yap)',
'Pacific/Wake' => 'Pacific/Wake (Wake Island)',
'Pacific/Wallis' => 'Pacific/Wallis'

                     ));

$smarty->display('system.tpl');

?>
